apiVersion: apps/v1
kind: Deployment
metadata:
  name: marco-nico
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marco-nico-app  # Ensure this label matches with template.labels
  template:
    metadata:
      labels:
        app: marco-nico-app  # Labels must match for proper pod management
        run-on-fargate: "true"  # This label ensures the pod runs on Fargate
    spec:
      containers:
        - name: marco-nico-container
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"