apiVersion: v1
kind: Service
metadata:
  name: marco-nico-service
  namespace: default
spec:
  selector:
    app: marco-nico-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer