apiVersion: apps/v1
kind: Deployment
metadata:
  name: marco-polo  # Updated the deployment name
  namespace: default  # Or replace with the namespace you use
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marco-polo
  template:
    metadata:
      labels:
        app: marco-polo
    spec:
      containers:
        - name: marco-polo
          image: marcuss/go-everywhere:latest
          ports:
            - containerPort: 80
            - containerPort: 443