apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default  # Or replace with the namespace you use
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: marcuss/go-everywhere:latest
          ports:
            - containerPort: 80
            - containerPort: 443