github_user             = "marcuss"
github_repo             = "go-everywhere"
aws_region              = "us-east-2"
environment             = "dev"
aws_eks_cluster_name    = "dev-cluster"
aws_eks_cluster_version = "1.31"
business_unit           = "goEverywhere"
local_machine_aws_user  = "eks-cluster-admin"