azure_region              = "East US 2"
github_user               = "marcuss"
github_repo               = "go-everywhere"
business_unit             = "goEverywhere"
local_machine_azure_user  = "aks-cluster-admin"
azure_aks_cluster_version = "1.29.9"
azure_aks_cluster_name  = "dev-cluster"