name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  set-environment:
    steps:
      - name: Set ENV Variables
        run: echo "Setting ENV variables"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

  build:
    permissions:
      id-token: write  # allows creation of an OIDC token
      contents: read
    uses: ./.github/workflows/build-steps.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image URI
        run: echo "IMAGE_URI=${{ needs.build.outputs.image }}" >> $GITHUB_ENV

      - name: Deploy to EKS
        uses: ./.github/workflows/deploy-steps.yml
        with:
          image: ${{ needs.build.outputs.image }}