name: Stop and Delete Pods and Service

on:
  workflow_dispatch:

jobs:
  stop-pods:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # allows creation of an OIDC token
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246386308913:role/eks-federated-deployer
          role-session-name: eks-deployer-temporal-session
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: Assume actual deployer role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/eks-deployer
          role-session-name: eks-deployer-temporal-session
          role-chaining: true

      - name: Create kube-config directory
        run: mkdir -p $HOME/.kube

      - name: Decode and set kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version

      - name: Stop the marco-nico pods by scaling down the deployment
        run: |
          kubectl scale deployment marco-nico --replicas=0 -n default

      - name: Delete the marco-nico deployment
        run: |
          kubectl delete deployment marco-nico -n default

      - name: Delete the marco-nico service
        run: |
          kubectl delete service marco-nico-service -n default