name: Stop All Pods

on:
  workflow_dispatch:

jobs:
  stop-pods:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # allows creation of an OIDC token

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ROLE
          role-session-name: stop-pods-session
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create kube-config directory
        run: mkdir -p $HOME/.kube

      - name: Decode and set kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version

      - name: Stop all pods by scaling down deployments and statefulsets
        run: |
          for ns in $(kubectl get namespaces -o jsonpath="{.items[*].metadata.name}"); do
            for deploy in $(kubectl get deployments -n $ns -o jsonpath="{.items[*].metadata.name}"); do
              kubectl scale deployment $deploy --replicas=0 -n $ns;
            done;
            for sts in $(kubectl get statefulsets -n $ns -o jsonpath="{.items[*].metadata.name}"); do
              kubectl scale statefulset $sts --replicas=0 -n $ns;
            done;
          done